# Generated by Django 3.0.6 on 2020-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalgallery', '0002_auto_20200524_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_image',
            field=models.ImageField(default='1', upload_to='images/'),
        ),
    ]
