# Generated by Django 3.0.6 on 2020-05-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalgallery', '0003_image_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
    ]
