# Generated by Django 3.0.6 on 2020-05-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalgallery', '0004_remove_image_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='editor',
            new_name='username',
        ),
    ]
