# Generated by Django 3.0.6 on 2020-05-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalgallery', '0006_location_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image_name',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='personalgallery.Editor'),
        ),
    ]
