# Generated by Django 3.0.6 on 2020-05-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalgallery', '0007_auto_20200524_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='username',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image_name',
        ),
        migrations.AlterField(
            model_name='image',
            name='post_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
