# Generated by Django 3.0.6 on 2020-05-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalgallery', '0008_auto_20200524_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post_image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
