# Generated by Django 3.0.6 on 2020-05-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalgallery', '0009_auto_20200525_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='image',
            name='image_category',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
