# Generated by Django 3.0.6 on 2020-05-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalgallery', '0010_auto_20200525_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_category',
        ),
    ]
