# Generated by Django 3.0.6 on 2020-05-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalgallery', '0011_remove_image_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
